version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: Oracle123
  backend:
    build: ./WebAPI
    container_name: webapi
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - oracle-db
  frontend:
    build: ./Web
    container_name: web
    ports:
      - "4200:4200"
    depends_on:
      - backend
